[default]
title = "CMS"
description = "A simple CMS written in Rust"
[database]
# Instead of localhost, you have to use an IP address 127.0.0.1
host = "127.0.0.1"
port = 3307
user = "cms"
password = "cmspassword"
name = "cms"