//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::comments::Entity as Comments;
pub use super::groups::Entity as Groups;
pub use super::groups_spaces::Entity as GroupsSpaces;
pub use super::groups_users::Entity as GroupsUsers;
pub use super::posts::Entity as Posts;
pub use super::roles::Entity as Roles;
pub use super::spaces::Entity as Spaces;
pub use super::users::Entity as Users;
